// IPL 2026 squads — sourced from Wikipedia team season pages + the
// 2026 personnel-changes page. Roles in a few cases were obvious
// Wikipedia errors (e.g. Sarfaraz Khan listed as "bowler", Vaibhav
// Sooryavanshi listed as "bowler") — those have been hand-corrected.
// Squads shift every auction; admin can edit this file or use the
// "+ Add player" modal on the create-contract form.
//
// Headshots exist today for: Dhoni, Kohli, Rohit, Hardik, Bumrah.
// All other players fall back to initials on team primary colour.

module.exports = [
  // ── CSK ─────────────────────────────────────────────
  { name: 'Ruturaj Gaikwad',   team_short: 'CSK',  role: 'batter'     },
  { name: 'MS Dhoni',          team_short: 'CSK',  role: 'wk',          headshot_path: '/players/dhoni.jpg' },
  { name: 'Sanju Samson',      team_short: 'CSK',  role: 'wk'         },
  { name: 'Matthew Short',     team_short: 'CSK',  role: 'batter'     },
  { name: 'Dewald Brevis',     team_short: 'CSK',  role: 'all-rounder' },
  { name: 'Shivam Dube',       team_short: 'CSK',  role: 'all-rounder' },
  { name: 'Kartik Sharma',     team_short: 'CSK',  role: 'batter'     },
  { name: 'Urvil Patel',       team_short: 'CSK',  role: 'batter'     },
  { name: 'Ayush Mhatre',      team_short: 'CSK',  role: 'batter'     },
  { name: 'Sarfaraz Khan',     team_short: 'CSK',  role: 'batter'     },
  { name: 'Gurjapneet Singh',  team_short: 'CSK',  role: 'bowler'     },
  { name: 'Prashant Veer',     team_short: 'CSK',  role: 'bowler'     },
  { name: 'Noor Ahmad',        team_short: 'CSK',  role: 'bowler'     },
  { name: 'Rahul Chahar',      team_short: 'CSK',  role: 'bowler'     },
  { name: 'Shreyas Gopal',     team_short: 'CSK',  role: 'bowler'     },
  { name: 'Akeal Hosein',      team_short: 'CSK',  role: 'bowler'     },
  { name: 'Aman Hakim Khan',   team_short: 'CSK',  role: 'bowler'     },
  { name: 'Matt Henry',        team_short: 'CSK',  role: 'bowler'     },
  { name: 'Zak Foulkes',       team_short: 'CSK',  role: 'bowler'     },
  { name: 'Spencer Johnson',   team_short: 'CSK',  role: 'bowler'     },
  { name: 'Anshul Kamboj',     team_short: 'CSK',  role: 'bowler'     },
  { name: 'Khaleel Ahmed',     team_short: 'CSK',  role: 'bowler'     },
  { name: 'Nathan Ellis',      team_short: 'CSK',  role: 'bowler'     },
  { name: 'Jamie Overton',     team_short: 'CSK',  role: 'all-rounder' },
  { name: 'Mukesh Choudhary',  team_short: 'CSK',  role: 'bowler'     },
  { name: 'Ramakrishna Ghosh', team_short: 'CSK',  role: 'bowler'     },

  // ── MI ──────────────────────────────────────────────
  { name: 'Hardik Pandya',       team_short: 'MI',   role: 'all-rounder', headshot_path: '/players/hardik.jpg' },
  { name: 'Rohit Sharma',        team_short: 'MI',   role: 'batter',      headshot_path: '/players/rohit.jpg' },
  { name: 'Jasprit Bumrah',      team_short: 'MI',   role: 'bowler',      headshot_path: '/players/bumrah.jpg' },
  { name: 'Suryakumar Yadav',    team_short: 'MI',   role: 'batter'     },
  { name: 'Trent Boult',         team_short: 'MI',   role: 'bowler'     },
  { name: 'Deepak Chahar',       team_short: 'MI',   role: 'bowler'     },
  { name: 'Tilak Varma',         team_short: 'MI',   role: 'batter'     },
  { name: 'Will Jacks',          team_short: 'MI',   role: 'all-rounder' },
  { name: 'Naman Dhir',          team_short: 'MI',   role: 'batter'     },
  { name: 'Allah Ghazanfar',     team_short: 'MI',   role: 'bowler'     },
  { name: 'Sherfane Rutherford', team_short: 'MI',   role: 'all-rounder' },
  { name: 'Shardul Thakur',      team_short: 'MI',   role: 'all-rounder' },
  { name: 'Mitchell Santner',    team_short: 'MI',   role: 'all-rounder' },
  { name: 'Ryan Rickelton',      team_short: 'MI',   role: 'wk'         },
  { name: 'Corbin Bosch',        team_short: 'MI',   role: 'all-rounder' },
  { name: 'Robin Minz',          team_short: 'MI',   role: 'wk'         },
  { name: 'Raj Angad Bawa',      team_short: 'MI',   role: 'all-rounder' },
  { name: 'Ashwani Kumar',       team_short: 'MI',   role: 'bowler'     },
  { name: 'Raghu Sharma',        team_short: 'MI',   role: 'bowler'     },
  { name: 'Mayank Markande',     team_short: 'MI',   role: 'bowler'     },
  { name: 'Vignesh Puthur',      team_short: 'MI',   role: 'bowler'     },
  { name: 'Danish Malewar',      team_short: 'MI',   role: 'batter'     },

  // ── RCB ─────────────────────────────────────────────
  { name: 'Rajat Patidar',      team_short: 'RCB',  role: 'batter'     },
  { name: 'Virat Kohli',        team_short: 'RCB',  role: 'batter',     headshot_path: '/players/kohli.jpg' },
  { name: 'Phil Salt',          team_short: 'RCB',  role: 'wk'         },
  { name: 'Jitesh Sharma',      team_short: 'RCB',  role: 'wk'         },
  { name: 'Tim David',          team_short: 'RCB',  role: 'batter'     },
  { name: 'Jacob Bethell',      team_short: 'RCB',  role: 'all-rounder' },
  { name: 'Devdutt Padikkal',   team_short: 'RCB',  role: 'batter'     },
  { name: 'Krunal Pandya',      team_short: 'RCB',  role: 'all-rounder' },
  { name: 'Venkatesh Iyer',     team_short: 'RCB',  role: 'all-rounder' },
  { name: 'Swapnil Singh',      team_short: 'RCB',  role: 'all-rounder' },
  { name: 'Abhinandan Singh',   team_short: 'RCB',  role: 'bowler'     },
  { name: 'Romario Shepherd',   team_short: 'RCB',  role: 'all-rounder' },
  { name: 'Josh Hazlewood',     team_short: 'RCB',  role: 'bowler'     },
  { name: 'Bhuvneshwar Kumar',  team_short: 'RCB',  role: 'bowler'     },
  { name: 'Rasikh Salam',       team_short: 'RCB',  role: 'bowler'     },
  { name: 'Yash Dayal',         team_short: 'RCB',  role: 'bowler'     },
  { name: 'Suyash Sharma',      team_short: 'RCB',  role: 'bowler'     },
  { name: 'Nuwan Thushara',     team_short: 'RCB',  role: 'bowler'     },
  { name: 'Jacob Duffy',        team_short: 'RCB',  role: 'bowler'     },
  { name: 'Jordan Cox',         team_short: 'RCB',  role: 'wk'         },

  // ── RR ──────────────────────────────────────────────
  { name: 'Riyan Parag',          team_short: 'RR',   role: 'all-rounder' },
  { name: 'Jofra Archer',         team_short: 'RR',   role: 'bowler'     },
  { name: 'Yashasvi Jaiswal',     team_short: 'RR',   role: 'batter'     },
  { name: 'Ravindra Jadeja',      team_short: 'RR',   role: 'all-rounder' },
  { name: 'Dhruv Jurel',          team_short: 'RR',   role: 'wk'         },
  { name: 'Shimron Hetmyer',      team_short: 'RR',   role: 'batter'     },
  { name: 'Tushar Deshpande',     team_short: 'RR',   role: 'bowler'     },
  { name: 'Sandeep Sharma',       team_short: 'RR',   role: 'bowler'     },
  { name: 'Nandre Burger',        team_short: 'RR',   role: 'bowler'     },
  { name: 'Sam Curran',           team_short: 'RR',   role: 'all-rounder' },
  { name: 'Kwena Maphaka',        team_short: 'RR',   role: 'bowler'     },
  { name: 'Vaibhav Sooryavanshi', team_short: 'RR',   role: 'batter'     },
  { name: 'Donovan Ferreira',     team_short: 'RR',   role: 'batter'     },
  { name: 'Shubham Dubey',        team_short: 'RR',   role: 'batter'     },
  { name: 'Yudhvir Singh',        team_short: 'RR',   role: 'bowler'     },
  { name: 'Lhuan-dre Pretorius',  team_short: 'RR',   role: 'wk'         },
  { name: 'Wanindu Hasaranga',    team_short: 'RR',   role: 'all-rounder' },
  { name: 'Ravi Bishnoi',         team_short: 'RR',   role: 'bowler'     },
  { name: 'Sushant Mishra',       team_short: 'RR',   role: 'bowler'     },
  { name: 'Ashok Sharma',         team_short: 'RR',   role: 'bowler'     },
  { name: 'Yash Raj Punja',       team_short: 'RR',   role: 'bowler'     },
  { name: 'Adam Milne',           team_short: 'RR',   role: 'bowler'     },
  { name: 'Kuldeep Sen',          team_short: 'RR',   role: 'bowler'     },
  { name: 'Aman Rao',             team_short: 'RR',   role: 'batter'     },

  // ── DC ──────────────────────────────────────────────
  { name: 'Axar Patel',           team_short: 'DC',   role: 'all-rounder' },
  { name: 'KL Rahul',             team_short: 'DC',   role: 'batter'     },
  { name: 'David Miller',         team_short: 'DC',   role: 'batter'     },
  { name: 'Sameer Rizvi',         team_short: 'DC',   role: 'all-rounder' },
  { name: 'Kuldeep Yadav',        team_short: 'DC',   role: 'bowler'     },
  { name: 'Abhishek Porel',       team_short: 'DC',   role: 'wk'         },
  { name: 'Vipraj Nigam',         team_short: 'DC',   role: 'bowler'     },
  { name: 'Tristan Stubbs',       team_short: 'DC',   role: 'batter'     },
  { name: 'Mukesh Kumar',         team_short: 'DC',   role: 'bowler'     },
  { name: 'Tripurana Vijay',      team_short: 'DC',   role: 'bowler'     },
  { name: 'Mitchell Starc',       team_short: 'DC',   role: 'bowler'     },
  { name: 'Dushmantha Chameera',  team_short: 'DC',   role: 'bowler'     },
  { name: 'Ajay Mandal',          team_short: 'DC',   role: 'bowler'     },
  { name: 'Karun Nair',           team_short: 'DC',   role: 'batter'     },
  { name: 'T Natarajan',          team_short: 'DC',   role: 'bowler'     },
  { name: 'Ashutosh Sharma',      team_short: 'DC',   role: 'batter'     },
  { name: 'Madhav Tiwari',        team_short: 'DC',   role: 'bowler'     },
  { name: 'Nitish Rana',          team_short: 'DC',   role: 'all-rounder' },
  { name: 'Ben Duckett',          team_short: 'DC',   role: 'batter'     },
  { name: 'Kyle Jamieson',        team_short: 'DC',   role: 'bowler'     },
  { name: 'Lungi Ngidi',          team_short: 'DC',   role: 'bowler'     },
  { name: 'Pathum Nissanka',      team_short: 'DC',   role: 'batter'     },
  { name: 'Prithvi Shaw',         team_short: 'DC',   role: 'batter'     },
  { name: 'Auqib Nabi',           team_short: 'DC',   role: 'bowler'     },
  { name: 'Sahil Ulhas Parakh',   team_short: 'DC',   role: 'bowler'     },

  // ── KKR ─────────────────────────────────────────────
  { name: 'Ajinkya Rahane',       team_short: 'KKR',  role: 'batter'     },
  { name: 'Rinku Singh',          team_short: 'KKR',  role: 'batter'     },
  { name: 'Angkrish Raghuvanshi', team_short: 'KKR',  role: 'batter'     },
  { name: 'Manish Pandey',        team_short: 'KKR',  role: 'batter'     },
  { name: 'Rovman Powell',        team_short: 'KKR',  role: 'batter'     },
  { name: 'Rahul Tripathi',       team_short: 'KKR',  role: 'batter'     },
  { name: 'Finn Allen',           team_short: 'KKR',  role: 'wk'         },
  { name: 'Tejasvi Singh',        team_short: 'KKR',  role: 'wk'         },
  { name: 'Tim Seifert',          team_short: 'KKR',  role: 'wk'         },
  { name: 'Sunil Narine',         team_short: 'KKR',  role: 'all-rounder' },
  { name: 'Anukul Roy',           team_short: 'KKR',  role: 'all-rounder' },
  { name: 'Ramandeep Singh',      team_short: 'KKR',  role: 'all-rounder' },
  { name: 'Cameron Green',        team_short: 'KKR',  role: 'all-rounder' },
  { name: 'Rachin Ravindra',      team_short: 'KKR',  role: 'all-rounder' },
  { name: 'Sarthak Ranjan',       team_short: 'KKR',  role: 'all-rounder' },
  { name: 'Daksh Kamra',          team_short: 'KKR',  role: 'all-rounder' },
  { name: 'Vaibhav Arora',        team_short: 'KKR',  role: 'bowler'     },
  { name: 'Umran Malik',          team_short: 'KKR',  role: 'bowler'     },
  { name: 'Matheesha Pathirana',  team_short: 'KKR',  role: 'bowler'     },
  { name: 'Kartik Tyagi',         team_short: 'KKR',  role: 'bowler'     },
  { name: 'Blessing Muzarabani',  team_short: 'KKR',  role: 'bowler'     },
  { name: 'Saurabh Dubey',        team_short: 'KKR',  role: 'bowler'     },
  { name: 'Navdeep Saini',        team_short: 'KKR',  role: 'bowler'     },
  { name: 'Prashant Solanki',     team_short: 'KKR',  role: 'bowler'     },
  { name: 'Varun Chakravarthy',   team_short: 'KKR',  role: 'bowler'     },

  // ── PBKS ────────────────────────────────────────────
  { name: 'Shreyas Iyer',          team_short: 'PBKS', role: 'batter'     },
  { name: 'Arshdeep Singh',        team_short: 'PBKS', role: 'bowler'     },
  { name: 'Yuzvendra Chahal',      team_short: 'PBKS', role: 'bowler'     },
  { name: 'Marcus Stoinis',        team_short: 'PBKS', role: 'all-rounder' },
  { name: 'Marco Jansen',          team_short: 'PBKS', role: 'all-rounder' },
  { name: 'Shashank Singh',        team_short: 'PBKS', role: 'batter'     },
  { name: 'Nehal Wadhera',         team_short: 'PBKS', role: 'batter'     },
  { name: 'Prabhsimran Singh',     team_short: 'PBKS', role: 'wk'         },
  { name: 'Priyansh Arya',         team_short: 'PBKS', role: 'batter'     },
  { name: 'Mitchell Owen',         team_short: 'PBKS', role: 'all-rounder' },
  { name: 'Azmatullah Omarzai',    team_short: 'PBKS', role: 'all-rounder' },
  { name: 'Lockie Ferguson',       team_short: 'PBKS', role: 'bowler'     },
  { name: 'Vijaykumar Vyshak',     team_short: 'PBKS', role: 'bowler'     },
  { name: 'Yash Thakur',           team_short: 'PBKS', role: 'bowler'     },
  { name: 'Harpreet Brar',         team_short: 'PBKS', role: 'all-rounder' },
  { name: 'Vishnu Vinod',          team_short: 'PBKS', role: 'wk'         },
  { name: 'Xavier Bartlett',       team_short: 'PBKS', role: 'bowler'     },
  { name: 'Pyla Avinash',          team_short: 'PBKS', role: 'batter'     },
  { name: 'Harnoor Pannu',         team_short: 'PBKS', role: 'batter'     },
  { name: 'Musheer Khan',          team_short: 'PBKS', role: 'all-rounder' },
  { name: 'Suryansh Shedge',       team_short: 'PBKS', role: 'batter'     },
  { name: 'Ben Dwarshuis',         team_short: 'PBKS', role: 'all-rounder' },
  { name: 'Josh Inglis',           team_short: 'PBKS', role: 'wk'         },

  // ── SRH ─────────────────────────────────────────────
  { name: 'Pat Cummins',          team_short: 'SRH',  role: 'all-rounder' },
  { name: 'Ishan Kishan',         team_short: 'SRH',  role: 'wk'         },
  { name: 'Travis Head',          team_short: 'SRH',  role: 'batter'     },
  { name: 'Heinrich Klaasen',     team_short: 'SRH',  role: 'wk'         },
  { name: 'Aniket Verma',         team_short: 'SRH',  role: 'batter'     },
  { name: 'Smaran Ravichandran',  team_short: 'SRH',  role: 'batter'     },
  { name: 'Salil Arora',          team_short: 'SRH',  role: 'wk'         },
  { name: 'Abhishek Sharma',      team_short: 'SRH',  role: 'all-rounder' },
  { name: 'Nitish Kumar Reddy',   team_short: 'SRH',  role: 'all-rounder' },
  { name: 'Shivam Mavi',          team_short: 'SRH',  role: 'bowler'     },
  { name: 'Shivang Kumar',        team_short: 'SRH',  role: 'all-rounder' },
  { name: 'Harsh Dubey',          team_short: 'SRH',  role: 'all-rounder' },
  { name: 'Liam Livingstone',     team_short: 'SRH',  role: 'all-rounder' },
  { name: 'Brydon Carse',         team_short: 'SRH',  role: 'all-rounder' },
  { name: 'Kamindu Mendis',       team_short: 'SRH',  role: 'all-rounder' },
  { name: 'Jack Edwards',         team_short: 'SRH',  role: 'all-rounder' },
  { name: 'Harshal Patel',        team_short: 'SRH',  role: 'bowler'     },
  { name: 'Jaydev Unadkat',       team_short: 'SRH',  role: 'bowler'     },
  { name: 'Eshan Malinga',        team_short: 'SRH',  role: 'bowler'     },
  { name: 'Praful Hinge',         team_short: 'SRH',  role: 'bowler'     },
  { name: 'Onkar Tarmale',        team_short: 'SRH',  role: 'bowler'     },
  { name: 'Sakib Hussain',        team_short: 'SRH',  role: 'bowler'     },
  { name: 'David Payne',          team_short: 'SRH',  role: 'bowler'     },
  { name: 'Zeeshan Ansari',       team_short: 'SRH',  role: 'bowler'     },
  { name: 'Amit Kumar',           team_short: 'SRH',  role: 'bowler'     },
  { name: 'Krains Fuletra',       team_short: 'SRH',  role: 'bowler'     },

  // ── GT ──────────────────────────────────────────────
  { name: 'Shubman Gill',          team_short: 'GT',   role: 'batter'     },
  { name: 'Rashid Khan',           team_short: 'GT',   role: 'bowler'     },
  { name: 'Jos Buttler',           team_short: 'GT',   role: 'wk'         },
  { name: 'Mohammed Siraj',        team_short: 'GT',   role: 'bowler'     },
  { name: 'Kagiso Rabada',         team_short: 'GT',   role: 'bowler'     },
  { name: 'Prasidh Krishna',       team_short: 'GT',   role: 'bowler'     },
  { name: 'Sai Sudarshan',         team_short: 'GT',   role: 'batter'     },
  { name: 'Rahul Tewatia',         team_short: 'GT',   role: 'all-rounder' },
  { name: 'Shahrukh Khan',         team_short: 'GT',   role: 'batter'     },
  { name: 'Washington Sundar',     team_short: 'GT',   role: 'all-rounder' },
  { name: 'Sai Kishore',           team_short: 'GT',   role: 'bowler'     },
  { name: 'Glenn Phillips',        team_short: 'GT',   role: 'all-rounder' },
  { name: 'Arshad Khan',           team_short: 'GT',   role: 'all-rounder' },
  { name: 'Gurnoor Singh Brar',    team_short: 'GT',   role: 'bowler'     },
  { name: 'Ishant Sharma',         team_short: 'GT',   role: 'bowler'     },
  { name: 'Jayant Yadav',          team_short: 'GT',   role: 'bowler'     },
  { name: 'Kumar Kushagra',        team_short: 'GT',   role: 'wk'         },
  { name: 'Anuj Rawat',            team_short: 'GT',   role: 'wk'         },
  { name: 'Manav Suthar',          team_short: 'GT',   role: 'bowler'     },
  { name: 'Nishant Sindhu',        team_short: 'GT',   role: 'all-rounder' },
  { name: 'Jason Holder',          team_short: 'GT',   role: 'all-rounder' },
  { name: 'Tom Banton',            team_short: 'GT',   role: 'wk'         },

  // ── LSG ─────────────────────────────────────────────
  { name: 'Rishabh Pant',          team_short: 'LSG',  role: 'wk'         },
  { name: 'Nicholas Pooran',       team_short: 'LSG',  role: 'wk'         },
  { name: 'Mayank Yadav',          team_short: 'LSG',  role: 'bowler'     },
  { name: 'Mohammed Shami',        team_short: 'LSG',  role: 'bowler'     },
  { name: 'Avesh Khan',            team_short: 'LSG',  role: 'bowler'     },
  { name: 'Abdul Samad',           team_short: 'LSG',  role: 'batter'     },
  { name: 'Ayush Badoni',          team_short: 'LSG',  role: 'batter'     },
  { name: 'Mohsin Khan',           team_short: 'LSG',  role: 'bowler'     },
  { name: 'Mitchell Marsh',        team_short: 'LSG',  role: 'all-rounder' },
  { name: 'Shahbaz Ahmed',         team_short: 'LSG',  role: 'all-rounder' },
  { name: 'Aiden Markram',         team_short: 'LSG',  role: 'batter'     },
  { name: 'Manimaran Siddharth',   team_short: 'LSG',  role: 'bowler'     },
  { name: 'Matthew Breetzke',      team_short: 'LSG',  role: 'batter'     },
  { name: 'Akash Singh',           team_short: 'LSG',  role: 'bowler'     },
  { name: 'Arjun Tendulkar',       team_short: 'LSG',  role: 'bowler'     },
  { name: 'Arshin Kulkarni',       team_short: 'LSG',  role: 'batter'     },
  { name: 'Himmat Singh',          team_short: 'LSG',  role: 'batter'     },
  { name: 'Digvesh Rathi',         team_short: 'LSG',  role: 'bowler'     },
  { name: 'Prince Yadav',          team_short: 'LSG',  role: 'bowler'     },
  { name: 'Akash Deep',            team_short: 'LSG',  role: 'bowler'     },
  { name: 'Anrich Nortje',         team_short: 'LSG',  role: 'bowler'     },
  { name: 'Mukul Choudhary',       team_short: 'LSG',  role: 'wk'         },
  { name: 'Naman Tiwari',          team_short: 'LSG',  role: 'bowler'     },
];
