// IPL 2026 squads — auto-generated from iplt20.com canonical squads on
// 2026-04-22 by server/scripts/regenerate-seed.js.
// Source of truth: server/scripts/ipl-canonical-squads.json.
// Re-run the generator to refresh after an audit.

module.exports = [
  // ── CSK ─────────────────────────────────────────────
  { name: "Akeal Hosein"                  , team_short: 'CSK' , role: 'bowler'     , ipl_id: 5608 },
  { name: "Aman Khan"                     , team_short: 'CSK' , role: 'batter'     , ipl_id: 20581 },
  { name: "Anshul Kamboj"                 , team_short: 'CSK' , role: 'bowler'     , ipl_id: 20702 },
  { name: "Ayush Mhatre"                  , team_short: 'CSK' , role: 'batter'     , ipl_id: 22377 },
  { name: "Dewald Brevis"                 , team_short: 'CSK' , role: 'batter'     , ipl_id: 20593 },
  { name: "Gurjapneet Singh"              , team_short: 'CSK' , role: 'bowler'     , ipl_id: 22032 },
  { name: "Jamie Overton"                 , team_short: 'CSK' , role: 'all-rounder', ipl_id: 22109 },
  { name: "Kartik Sharma"                 , team_short: 'CSK' , role: 'wk'         , ipl_id: 23012 },
  { name: "Khaleel Ahmed"                 , team_short: 'CSK' , role: 'bowler'     , ipl_id: 2964 },
  { name: "Matt Henry"                    , team_short: 'CSK' , role: 'bowler'     , ipl_id: 1505 },
  { name: "Matthew William Short"         , team_short: 'CSK' , role: 'batter'     , ipl_id: 2032 },
  { name: "MS Dhoni"                      , team_short: 'CSK' , role: 'wk'         , ipl_id: 1 },
  { name: "Mukesh Choudhary"              , team_short: 'CSK' , role: 'bowler'     , ipl_id: 20575 },
  { name: "Noor Ahmad"                    , team_short: 'CSK' , role: 'bowler'     , ipl_id: 20590 },
  { name: "Prashant Veer"                 , team_short: 'CSK' , role: 'all-rounder', ipl_id: 23008 },
  { name: "Rahul Chahar"                  , team_short: 'CSK' , role: 'bowler'     , ipl_id: 3763 },
  { name: "Ramakrishna Ghosh"             , team_short: 'CSK' , role: 'all-rounder', ipl_id: 22153 },
  { name: "Ruturaj Gaikwad"               , team_short: 'CSK' , role: 'batter'     , ipl_id: 5443 },
  { name: "Sanju Samson"                  , team_short: 'CSK' , role: 'wk'         , ipl_id: 258 },
  { name: "Sarfaraz Khan"                 , team_short: 'CSK' , role: 'batter'     , ipl_id: 1564 },
  { name: "Shivam Dube"                   , team_short: 'CSK' , role: 'all-rounder', ipl_id: 5431 },
  { name: "Shreyas Gopal"                 , team_short: 'CSK' , role: 'bowler'     , ipl_id: 20696 },
  { name: "Spencer Johnson"               , team_short: 'CSK' , role: 'bowler'     , ipl_id: 20699 },
  { name: "Urvil Patel"                   , team_short: 'CSK' , role: 'wk'         , ipl_id: 5653 },
  { name: "Zak Foulkes"                   , team_short: 'CSK' , role: 'all-rounder', ipl_id: 23022 },

  // ── MI ─────────────────────────────────────────────
  { name: "Allah Ghazanfar"               , team_short: 'MI'  , role: 'bowler'     , ipl_id: 20725 },
  { name: "Ashwani Kumar"                 , team_short: 'MI'  , role: 'bowler'     , ipl_id: 22030 },
  { name: "Corbin Bosch"                  , team_short: 'MI'  , role: 'all-rounder', ipl_id: 20680 },
  { name: "Danish Malewar"                , team_short: 'MI'  , role: 'batter'     , ipl_id: 23031 },
  { name: "Deepak Chahar"                 , team_short: 'MI'  , role: 'bowler'     , ipl_id: 140 },
  { name: "Hardik Pandya"                 , team_short: 'MI'  , role: 'all-rounder', ipl_id: 2740 },
  { name: "Jasprit Bumrah"                , team_short: 'MI'  , role: 'bowler'     , ipl_id: 1124 },
  { name: "Krish Bhagat"                  , team_short: 'MI'  , role: 'all-rounder', ipl_id: 33338 },
  { name: "Mayank Markande"               , team_short: 'MI'  , role: 'bowler'     , ipl_id: 4951 },
  { name: "Mayank Rawat"                  , team_short: 'MI'  , role: 'all-rounder', ipl_id: 23038 },
  { name: "Mitchell Santner"              , team_short: 'MI'  , role: 'all-rounder', ipl_id: 1903 },
  { name: "Mohammad Izhar"                , team_short: 'MI'  , role: 'bowler'     , ipl_id: 23045 },
  { name: "N. Tilak Varma"                , team_short: 'MI'  , role: 'batter'     , ipl_id: 20594 },
  { name: "Naman Dhir"                    , team_short: 'MI'  , role: 'all-rounder', ipl_id: 20701 },
  { name: "Quinton de Kock"               , team_short: 'MI'  , role: 'wk'         , ipl_id: 834 },
  { name: "Raghu Sharma"                  , team_short: 'MI'  , role: 'bowler'     , ipl_id: 22379 },
  { name: "Raj Angad Bawa"                , team_short: 'MI'  , role: 'all-rounder', ipl_id: 20601 },
  { name: "Robin Minz"                    , team_short: 'MI'  , role: 'wk'         , ipl_id: 20707 },
  { name: "Rohit Sharma"                  , team_short: 'MI'  , role: 'batter'     , ipl_id: 107 },
  { name: "Ryan Rickelton"                , team_short: 'MI'  , role: 'wk'         , ipl_id: 22003 },
  { name: "Shardul Thakur"                , team_short: 'MI'  , role: 'all-rounder', ipl_id: 1745 },
  { name: "Sherfane Rutherford"           , team_short: 'MI'  , role: 'batter'     , ipl_id: 5396 },
  { name: "Surya Kumar Yadav"             , team_short: 'MI'  , role: 'batter'     , ipl_id: 108 },
  { name: "Trent Boult"                   , team_short: 'MI'  , role: 'bowler'     , ipl_id: 969 },
  { name: "Will Jacks"                    , team_short: 'MI'  , role: 'all-rounder', ipl_id: 5629 },

  // ── RCB ─────────────────────────────────────────────
  { name: "Abhinandan Singh"              , team_short: 'RCB' , role: 'bowler'     , ipl_id: 22136 },
  { name: "Bhuvneshwar Kumar"             , team_short: 'RCB' , role: 'bowler'     , ipl_id: 116 },
  { name: "Devdutt Padikkal"              , team_short: 'RCB' , role: 'batter'     , ipl_id: 5430 },
  { name: "Jacob Bethell"                 , team_short: 'RCB' , role: 'all-rounder', ipl_id: 22074 },
  { name: "Jacob Duffy"                   , team_short: 'RCB' , role: 'bowler'     , ipl_id: 23003 },
  { name: "Jitesh Sharma"                 , team_short: 'RCB' , role: 'wk'         , ipl_id: 3185 },
  { name: "Jordan Cox"                    , team_short: 'RCB' , role: 'wk'         , ipl_id: 23023 },
  { name: "Josh Hazlewood"                , team_short: 'RCB' , role: 'bowler'     , ipl_id: 857 },
  { name: "Kanishk Chouhan"               , team_short: 'RCB' , role: 'all-rounder', ipl_id: 23168 },
  { name: "Krunal Pandya"                 , team_short: 'RCB' , role: 'all-rounder', ipl_id: 3183 },
  { name: "Mangesh Yadav"                 , team_short: 'RCB' , role: 'all-rounder', ipl_id: 23040 },
  { name: "Nuwan Thushara"                , team_short: 'RCB' , role: 'bowler'     , ipl_id: 20700 },
  { name: "Phil Salt"                     , team_short: 'RCB' , role: 'wk'         , ipl_id: 5606 },
  { name: "Rajat Patidar"                 , team_short: 'RCB' , role: 'batter'     , ipl_id: 5471 },
  { name: "Rasikh Dar"                    , team_short: 'RCB' , role: 'bowler'     , ipl_id: 20577 },
  { name: "Romario Shepherd"              , team_short: 'RCB' , role: 'all-rounder', ipl_id: 20609 },
  { name: "Satvik Deswal"                 , team_short: 'RCB' , role: 'all-rounder', ipl_id: 23036 },
  { name: "Suyash Sharma"                 , team_short: 'RCB' , role: 'bowler'     , ipl_id: 5668 },
  { name: "Swapnil Singh"                 , team_short: 'RCB' , role: 'all-rounder', ipl_id: 3180 },
  { name: "Tim David"                     , team_short: 'RCB' , role: 'all-rounder', ipl_id: 4524 },
  { name: "Venkatesh Iyer"                , team_short: 'RCB' , role: 'all-rounder', ipl_id: 8540 },
  { name: "Vicky Ostwal"                  , team_short: 'RCB' , role: 'bowler'     , ipl_id: 20624 },
  { name: "Vihaan Malhotra"               , team_short: 'RCB' , role: 'all-rounder', ipl_id: 23150 },
  { name: "Virat Kohli"                   , team_short: 'RCB' , role: 'batter'     , ipl_id: 164 },
  { name: "Yash Dayal"                    , team_short: 'RCB' , role: 'bowler'     , ipl_id: 20591 },

  // ── RR ─────────────────────────────────────────────
  { name: "Adam Milne"                    , team_short: 'RR'  , role: 'bowler'     , ipl_id: 434 },
  { name: "Aman Rao Perala"               , team_short: 'RR'  , role: 'batter'     , ipl_id: 23034 },
  { name: "Brijesh Sharma"                , team_short: 'RR'  , role: 'bowler'     , ipl_id: 23164 },
  { name: "Dasun Shanaka"                 , team_short: 'RR'  , role: 'all-rounder', ipl_id: 1095 },
  { name: "Dhruv Jurel"                   , team_short: 'RR'  , role: 'wk'         , ipl_id: 20620 },
  { name: "Donovan Ferreira"              , team_short: 'RR'  , role: 'wk'         , ipl_id: 5652 },
  { name: "Jofra Archer"                  , team_short: 'RR'  , role: 'bowler'     , ipl_id: 3502 },
  { name: "Kuldeep Sen"                   , team_short: 'RR'  , role: 'bowler'     , ipl_id: 20616 },
  { name: "Kwena Maphaka"                 , team_short: 'RR'  , role: 'bowler'     , ipl_id: 20724 },
  { name: "Lhuan-dre Pretorious"          , team_short: 'RR'  , role: 'wk'         , ipl_id: 22383 },
  { name: "Nandre Burger"                 , team_short: 'RR'  , role: 'bowler'     , ipl_id: 20716 },
  { name: "Ravi Bishnoi"                  , team_short: 'RR'  , role: 'bowler'     , ipl_id: 19351 },
  { name: "Ravi Singh"                    , team_short: 'RR'  , role: 'wk'         , ipl_id: 23044 },
  { name: "Ravindra Jadeja"               , team_short: 'RR'  , role: 'all-rounder', ipl_id: 9 },
  { name: "Riyan Parag"                   , team_short: 'RR'  , role: 'all-rounder', ipl_id: 4445 },
  { name: "Sandeep Sharma"                , team_short: 'RR'  , role: 'bowler'     , ipl_id: 1112 },
  { name: "Shimron Hetmyer"               , team_short: 'RR'  , role: 'batter'     , ipl_id: 1705 },
  { name: "Shubham Dubey"                 , team_short: 'RR'  , role: 'batter'     , ipl_id: 20688 },
  { name: "Sushant Mishra"                , team_short: 'RR'  , role: 'bowler'     , ipl_id: 20695 },
  { name: "Tushar Deshpande"              , team_short: 'RR'  , role: 'bowler'     , ipl_id: 3257 },
  { name: "Vaibhav Sooryavanshi"          , team_short: 'RR'  , role: 'batter'     , ipl_id: 22203 },
  { name: "Vignesh Puthur"                , team_short: 'RR'  , role: 'bowler'     , ipl_id: 22266 },
  { name: "Yash Raj Punja"                , team_short: 'RR'  , role: 'bowler'     , ipl_id: 23016 },
  { name: "Yashasvi Jaiswal"              , team_short: 'RR'  , role: 'batter'     , ipl_id: 13538 },
  { name: "Yudhvir Singh Charak"          , team_short: 'RR'  , role: 'all-rounder', ipl_id: 10842 },

  // ── DC ─────────────────────────────────────────────
  { name: "Abishek Porel"                 , team_short: 'DC'  , role: 'wk'         , ipl_id: 33333 },
  { name: "Ajay Mandal"                   , team_short: 'DC'  , role: 'all-rounder', ipl_id: 5811 },
  { name: "Ashutosh Sharma"               , team_short: 'DC'  , role: 'all-rounder', ipl_id: 20703 },
  { name: "Auqib Nabi"                    , team_short: 'DC'  , role: 'bowler'     , ipl_id: 23005 },
  { name: "Axar Patel"                    , team_short: 'DC'  , role: 'all-rounder', ipl_id: 1113 },
  { name: "Ben Duckett"                   , team_short: 'DC'  , role: 'wk'         , ipl_id: 23001 },
  { name: "David Miller"                  , team_short: 'DC'  , role: 'batter'     , ipl_id: 187 },
  { name: "Dushmantha Chameera"           , team_short: 'DC'  , role: 'bowler'     , ipl_id: 817 },
  { name: "Karun Nair"                    , team_short: 'DC'  , role: 'batter'     , ipl_id: 276 },
  { name: "KL Rahul"                      , team_short: 'DC'  , role: 'wk'         , ipl_id: 1125 },
  { name: "Kuldeep Yadav"                 , team_short: 'DC'  , role: 'bowler'     , ipl_id: 261 },
  { name: "Kyle Jamieson"                 , team_short: 'DC'  , role: 'bowler'     , ipl_id: 1616 },
  { name: "Lungisani Ngidi"               , team_short: 'DC'  , role: 'bowler'     , ipl_id: 3746 },
  { name: "Madhav Tiwari"                 , team_short: 'DC'  , role: 'all-rounder', ipl_id: 22259 },
  { name: "Mitchell Starc"                , team_short: 'DC'  , role: 'bowler'     , ipl_id: 490 },
  { name: "Mukesh Kumar"                  , team_short: 'DC'  , role: 'bowler'     , ipl_id: 5622 },
  { name: "Nitish Rana"                   , team_short: 'DC'  , role: 'all-rounder', ipl_id: 2738 },
  { name: "Pathum Nissanka"               , team_short: 'DC'  , role: 'batter'     , ipl_id: 23020 },
  { name: "Prithvi Shaw"                  , team_short: 'DC'  , role: 'batter'     , ipl_id: 3764 },
  { name: "Sahil Parakh"                  , team_short: 'DC'  , role: 'batter'     , ipl_id: 23063 },
  { name: "Sameer Rizvi"                  , team_short: 'DC'  , role: 'all-rounder', ipl_id: 20689 },
  { name: "T. Natarajan"                  , team_short: 'DC'  , role: 'bowler'     , ipl_id: 3831 },
  { name: "Tripurana Vijay"               , team_short: 'DC'  , role: 'all-rounder', ipl_id: 22252 },
  { name: "Tristan Stubbs"                , team_short: 'DC'  , role: 'wk'         , ipl_id: 20631 },
  { name: "Vipraj Nigam"                  , team_short: 'DC'  , role: 'all-rounder', ipl_id: 22053 },

  // ── KKR ─────────────────────────────────────────────
  { name: "Ajinkya Rahane"                , team_short: 'KKR' , role: 'batter'     , ipl_id: 135 },
  { name: "Angkrish Raghuvanshi"          , team_short: 'KKR' , role: 'batter'     , ipl_id: 20690 },
  { name: "Anukul Roy"                    , team_short: 'KKR' , role: 'all-rounder', ipl_id: 3774 },
  { name: "Blessing Muzarabani"           , team_short: 'KKR' , role: 'bowler'     , ipl_id: 22387 },
  { name: "Cameron Green"                 , team_short: 'KKR' , role: 'all-rounder', ipl_id: 5602 },
  { name: "Daksh Kamra"                   , team_short: 'KKR' , role: 'all-rounder', ipl_id: 23177 },
  { name: "Finn Allen"                    , team_short: 'KKR' , role: 'wk'         , ipl_id: 3020 },
  { name: "Kartik Tyagi"                  , team_short: 'KKR' , role: 'bowler'     , ipl_id: 10059 },
  { name: "Manish Pandey"                 , team_short: 'KKR' , role: 'batter'     , ipl_id: 123 },
  { name: "Matheesha Pathirana"           , team_short: 'KKR' , role: 'bowler'     , ipl_id: 20627 },
  { name: "Navdeep Saini"                 , team_short: 'KKR' , role: 'bowler'     , ipl_id: 3824 },
  { name: "Prashant Solanki"              , team_short: 'KKR' , role: 'bowler'     , ipl_id: 20576 },
  { name: "Rachin Ravindra"               , team_short: 'KKR' , role: 'all-rounder', ipl_id: 20684 },
  { name: "Rahul Tripathi"                , team_short: 'KKR' , role: 'batter'     , ipl_id: 3838 },
  { name: "Ramandeep Singh"               , team_short: 'KKR' , role: 'all-rounder', ipl_id: 20595 },
  { name: "Rinku Singh"                   , team_short: 'KKR' , role: 'batter'     , ipl_id: 3830 },
  { name: "Rovman Powell"                 , team_short: 'KKR' , role: 'batter'     , ipl_id: 3333 },
  { name: "Sarthak Ranjan"                , team_short: 'KKR' , role: 'all-rounder', ipl_id: 23154 },
  { name: "Saurabh Dubey"                 , team_short: 'KKR' , role: 'bowler'     , ipl_id: 20612 },
  { name: "Sunil Narine"                  , team_short: 'KKR' , role: 'all-rounder', ipl_id: 203 },
  { name: "Tejasvi Singh"                 , team_short: 'KKR' , role: 'wk'         , ipl_id: 23013 },
  { name: "Tim Seifert"                   , team_short: 'KKR' , role: 'wk'         , ipl_id: 1619 },
  { name: "Umran Malik"                   , team_short: 'KKR' , role: 'bowler'     , ipl_id: 15154 },
  { name: "Vaibhav Arora"                 , team_short: 'KKR' , role: 'bowler'     , ipl_id: 14859 },
  { name: "Varun Chakaravarthy"           , team_short: 'KKR' , role: 'bowler'     , ipl_id: 5432 },

  // ── PBKS ─────────────────────────────────────────────
  { name: "Arshdeep Singh"                , team_short: 'PBKS', role: 'bowler'     , ipl_id: 4698 },
  { name: "Azmatullah Omarzai"            , team_short: 'PBKS', role: 'all-rounder', ipl_id: 20685 },
  { name: "Ben Dwarshuis"                 , team_short: 'PBKS', role: 'bowler'     , ipl_id: 1478 },
  { name: "Cooper Connolly"               , team_short: 'PBKS', role: 'all-rounder', ipl_id: 23052 },
  { name: "Harnoor Pannu"                 , team_short: 'PBKS', role: 'batter'     , ipl_id: 22019 },
  { name: "Harpreet Brar"                 , team_short: 'PBKS', role: 'all-rounder', ipl_id: 5441 },
  { name: "Lockie Ferguson"               , team_short: 'PBKS', role: 'bowler'     , ipl_id: 3729 },
  { name: "Marco Jansen"                  , team_short: 'PBKS', role: 'all-rounder', ipl_id: 17068 },
  { name: "Marcus Stoinis"                , team_short: 'PBKS', role: 'all-rounder', ipl_id: 964 },
  { name: "Mitch Owen"                    , team_short: 'PBKS', role: 'all-rounder', ipl_id: 22380 },
  { name: "Musheer Khan"                  , team_short: 'PBKS', role: 'all-rounder', ipl_id: 22085 },
  { name: "Nehal Wadhera"                 , team_short: 'PBKS', role: 'batter'     , ipl_id: 5859 },
  { name: "Prabhsimran Singh"             , team_short: 'PBKS', role: 'wk'         , ipl_id: 5436 },
  { name: "Pravin Dubey"                  , team_short: 'PBKS', role: 'bowler'     , ipl_id: 3188 },
  { name: "Priyansh Arya"                 , team_short: 'PBKS', role: 'all-rounder', ipl_id: 22052 },
  { name: "Pyla Avinash"                  , team_short: 'PBKS', role: 'batter'     , ipl_id: 22145 },
  { name: "Shashank Singh"                , team_short: 'PBKS', role: 'batter'     , ipl_id: 3261 },
  { name: "Shreyas Iyer"                  , team_short: 'PBKS', role: 'batter'     , ipl_id: 1563 },
  { name: "Suryansh Shedge"               , team_short: 'PBKS', role: 'all-rounder', ipl_id: 20683 },
  { name: "Vishal Nishad"                 , team_short: 'PBKS', role: 'bowler'     , ipl_id: 23088 },
  { name: "Vishnu Vinod"                  , team_short: 'PBKS', role: 'wk'         , ipl_id: 4305 },
  { name: "Vyshak Vijaykumar"             , team_short: 'PBKS', role: 'bowler'     , ipl_id: 1097 },
  { name: "Xavier Bartlett"               , team_short: 'PBKS', role: 'bowler'     , ipl_id: 22112 },
  { name: "Yash Thakur"                   , team_short: 'PBKS', role: 'bowler'     , ipl_id: 5624 },
  { name: "Yuzvendra Chahal"              , team_short: 'PBKS', role: 'bowler'     , ipl_id: 111 },

  // ── SRH ─────────────────────────────────────────────
  { name: "Abhishek Sharma"               , team_short: 'SRH' , role: 'all-rounder', ipl_id: 3760 },
  { name: "Amit Kumar"                    , team_short: 'SRH' , role: 'bowler'     , ipl_id: 23087 },
  { name: "Aniket Verma"                  , team_short: 'SRH' , role: 'batter'     , ipl_id: 22082 },
  { name: "Dilshan Madushanka"            , team_short: 'SRH' , role: 'bowler'     , ipl_id: 33337 },
  { name: "Eshan Malinga"                 , team_short: 'SRH' , role: 'bowler'     , ipl_id: 22228 },
  { name: "Gerald Coetzee"                , team_short: 'SRH' , role: 'bowler'     , ipl_id: 20686 },
  { name: "Harsh Dubey"                   , team_short: 'SRH' , role: 'all-rounder', ipl_id: 22381 },
  { name: "Harshal Patel"                 , team_short: 'SRH' , role: 'all-rounder', ipl_id: 157 },
  { name: "Heinrich Klaasen"              , team_short: 'SRH' , role: 'wk'         , ipl_id: 3869 },
  { name: "Ishan Kishan"                  , team_short: 'SRH' , role: 'wk'         , ipl_id: 2975 },
  { name: "Jaydev Unadkat"                , team_short: 'SRH' , role: 'bowler'     , ipl_id: 86 },
  { name: "Kamindu Mendis"                , team_short: 'SRH' , role: 'all-rounder', ipl_id: 22077 },
  { name: "Krains Fuletra"                , team_short: 'SRH' , role: 'all-rounder', ipl_id: 23132 },
  { name: "Liam Livingstone"              , team_short: 'SRH' , role: 'all-rounder', ipl_id: 3644 },
  { name: "Nitish Kumar Reddy"            , team_short: 'SRH' , role: 'all-rounder', ipl_id: 5711 },
  { name: "Onkar Tarmale"                 , team_short: 'SRH' , role: 'bowler'     , ipl_id: 23048 },
  { name: "Pat Cummins"                   , team_short: 'SRH' , role: 'bowler'     , ipl_id: 488 },
  { name: "Praful Hinge"                  , team_short: 'SRH' , role: 'bowler'     , ipl_id: 23114 },
  { name: "Sakib Hussain"                 , team_short: 'SRH' , role: 'bowler'     , ipl_id: 20717 },
  { name: "Salil Arora"                   , team_short: 'SRH' , role: 'wk'         , ipl_id: 23041 },
  { name: "Shivam Mavi"                   , team_short: 'SRH' , role: 'bowler'     , ipl_id: 3779 },
  { name: "Shivang Kumar"                 , team_short: 'SRH' , role: 'all-rounder', ipl_id: 23006 },
  { name: "Smaran Ravichandran"           , team_short: 'SRH' , role: 'batter'     , ipl_id: 22378 },
  { name: "Travis Head"                   , team_short: 'SRH' , role: 'batter'     , ipl_id: 1020 },
  { name: "Zeeshan Ansari"                , team_short: 'SRH' , role: 'bowler'     , ipl_id: 22007 },

  // ── GT ─────────────────────────────────────────────
  { name: "Anuj Rawat"                    , team_short: 'GT'  , role: 'wk'         , ipl_id: 10788 },
  { name: "Ashok Sharma"                  , team_short: 'GT'  , role: 'bowler'     , ipl_id: 20584 },
  { name: "Connor Esterhuizen"            , team_short: 'GT'  , role: 'batter'     , ipl_id: 33339 },
  { name: "Glenn Phillips"                , team_short: 'GT'  , role: 'batter'     , ipl_id: 3027 },
  { name: "Gurnoor Singh Brar"            , team_short: 'GT'  , role: 'bowler'     , ipl_id: 1094 },
  { name: "Ishant Sharma"                 , team_short: 'GT'  , role: 'bowler'     , ipl_id: 38 },
  { name: "Jason Holder"                  , team_short: 'GT'  , role: 'all-rounder', ipl_id: 1075 },
  { name: "Jayant Yadav"                  , team_short: 'GT'  , role: 'all-rounder', ipl_id: 1740 },
  { name: "Jos Buttler"                   , team_short: 'GT'  , role: 'wk'         , ipl_id: 509 },
  { name: "Kagiso Rabada"                 , team_short: 'GT'  , role: 'bowler'     , ipl_id: 1664 },
  { name: "Kulwant Khejroliya"            , team_short: 'GT'  , role: 'bowler'     , ipl_id: 3835 },
  { name: "Kumar Kushagra"                , team_short: 'GT'  , role: 'wk'         , ipl_id: 20694 },
  { name: "Luke Wood"                     , team_short: 'GT'  , role: 'bowler'     , ipl_id: 20721 },
  { name: "Manav Suthar"                  , team_short: 'GT'  , role: 'bowler'     , ipl_id: 20692 },
  { name: "Mohammed Siraj"                , team_short: 'GT'  , role: 'bowler'     , ipl_id: 3840 },
  { name: "Mohd. Arshad Khan"             , team_short: 'GT'  , role: 'all-rounder', ipl_id: 20599 },
  { name: "Nishant Sindhu"                , team_short: 'GT'  , role: 'all-rounder', ipl_id: 5615 },
  { name: "Prasidh Krishna"               , team_short: 'GT'  , role: 'bowler'     , ipl_id: 5105 },
  { name: "Rahul Tewatia"                 , team_short: 'GT'  , role: 'all-rounder', ipl_id: 1749 },
  { name: "Rashid Khan"                   , team_short: 'GT'  , role: 'bowler'     , ipl_id: 2885 },
  { name: "Sai Kishore"                   , team_short: 'GT'  , role: 'all-rounder', ipl_id: 7123 },
  { name: "Sai Sudharsan"                 , team_short: 'GT'  , role: 'batter'     , ipl_id: 20592 },
  { name: "Shahrukh Khan"                 , team_short: 'GT'  , role: 'all-rounder', ipl_id: 7779 },
  { name: "Shubman Gill"                  , team_short: 'GT'  , role: 'batter'     , ipl_id: 3761 },
  { name: "Washington Sundar"             , team_short: 'GT'  , role: 'all-rounder', ipl_id: 2973 },

  // ── LSG ─────────────────────────────────────────────
  { name: "Abdul Samad"                   , team_short: 'LSG' , role: 'all-rounder', ipl_id: 19352 },
  { name: "Aiden Markram"                 , team_short: 'LSG' , role: 'batter'     , ipl_id: 1667 },
  { name: "Akash Singh"                   , team_short: 'LSG' , role: 'bowler'     , ipl_id: 12585 },
  { name: "Akshat Raghuwanshi"            , team_short: 'LSG' , role: 'batter'     , ipl_id: 23035 },
  { name: "Anrich Nortje"                 , team_short: 'LSG' , role: 'bowler'     , ipl_id: 5433 },
  { name: "Arjun Tendulkar"               , team_short: 'LSG' , role: 'bowler'     , ipl_id: 10244 },
  { name: "Arshin Kulkarni"               , team_short: 'LSG' , role: 'all-rounder', ipl_id: 20691 },
  { name: "Avesh Khan"                    , team_short: 'LSG' , role: 'bowler'     , ipl_id: 1561 },
  { name: "Ayush Badoni"                  , team_short: 'LSG' , role: 'all-rounder', ipl_id: 20586 },
  { name: "Digvesh Singh"                 , team_short: 'LSG' , role: 'bowler'     , ipl_id: 5847 },
  { name: "George Linde"                  , team_short: 'LSG' , role: 'all-rounder', ipl_id: 33336 },
  { name: "Himmat Singh"                  , team_short: 'LSG' , role: 'batter'     , ipl_id: 5434 },
  { name: "Josh Inglis"                   , team_short: 'LSG' , role: 'wk'         , ipl_id: 22372 },
  { name: "M. Siddharth"                  , team_short: 'LSG' , role: 'bowler'     , ipl_id: 7119 },
  { name: "Matthew Breetzke"              , team_short: 'LSG' , role: 'batter'     , ipl_id: 22375 },
  { name: "Mayank Yadav"                  , team_short: 'LSG' , role: 'bowler'     , ipl_id: 20585 },
  { name: "Mitchell Marsh"                , team_short: 'LSG' , role: 'all-rounder', ipl_id: 221 },
  { name: "Mohammad Shami"                , team_short: 'LSG' , role: 'bowler'     , ipl_id: 94 },
  { name: "Mohsin Khan"                   , team_short: 'LSG' , role: 'bowler'     , ipl_id: 4952 },
  { name: "Mukul Choudhary"               , team_short: 'LSG' , role: 'wk'         , ipl_id: 23010 },
  { name: "Naman Tiwari"                  , team_short: 'LSG' , role: 'bowler'     , ipl_id: 23015 },
  { name: "Nicholas Pooran"               , team_short: 'LSG' , role: 'wk'         , ipl_id: 1703 },
  { name: "Prince Yadav"                  , team_short: 'LSG' , role: 'bowler'     , ipl_id: 22097 },
  { name: "Rishabh Pant"                  , team_short: 'LSG' , role: 'wk'         , ipl_id: 2972 },
  { name: "Shahbaz Ahamad"                , team_short: 'LSG' , role: 'all-rounder', ipl_id: 13803 },

];